/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RSplatRouteImport } from './routes/r.$'
import { Route as AdminSlugsRouteImport } from './routes/admin.slugs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLatencyRouteImport } from './routes/admin.latency'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicHooksWarmupRouteImport } from './routes/api/public/hooks/warmup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlugsRoute = AdminSlugsRouteImport.update({
  id: '/slugs',
  path: '/slugs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLatencyRoute = AdminLatencyRouteImport.update({
  id: '/latency',
  path: '/latency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWarmupRoute = ApiPublicHooksWarmupRouteImport.update({
  id: '/api/public/hooks/warmup',
  path: '/api/public/hooks/warmup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/latency': typeof AdminLatencyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slugs': typeof AdminSlugsRoute
  '/r/$': typeof RSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/warmup': typeof ApiPublicHooksWarmupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/latency': typeof AdminLatencyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slugs': typeof AdminSlugsRoute
  '/r/$': typeof RSplatRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/warmup': typeof ApiPublicHooksWarmupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/latency': typeof AdminLatencyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slugs': typeof AdminSlugsRoute
  '/r/$': typeof RSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/warmup': typeof ApiPublicHooksWarmupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/domains'
    | '/admin/events'
    | '/admin/latency'
    | '/admin/settings'
    | '/admin/slugs'
    | '/r/$'
    | '/admin/'
    | '/api/public/health'
    | '/api/public/hooks/warmup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/admin/analytics'
    | '/admin/domains'
    | '/admin/events'
    | '/admin/latency'
    | '/admin/settings'
    | '/admin/slugs'
    | '/r/$'
    | '/admin'
    | '/api/public/health'
    | '/api/public/hooks/warmup'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/domains'
    | '/admin/events'
    | '/admin/latency'
    | '/admin/settings'
    | '/admin/slugs'
    | '/r/$'
    | '/admin/'
    | '/api/public/health'
    | '/api/public/hooks/warmup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RSplatRoute: typeof RSplatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksWarmupRoute: typeof ApiPublicHooksWarmupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/slugs': {
      id: '/admin/slugs'
      path: '/slugs'
      fullPath: '/admin/slugs'
      preLoaderRoute: typeof AdminSlugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/latency': {
      id: '/admin/latency'
      path: '/latency'
      fullPath: '/admin/latency'
      preLoaderRoute: typeof AdminLatencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/warmup': {
      id: '/api/public/hooks/warmup'
      path: '/api/public/hooks/warmup'
      fullPath: '/api/public/hooks/warmup'
      preLoaderRoute: typeof ApiPublicHooksWarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLatencyRoute: typeof AdminLatencyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlugsRoute: typeof AdminSlugsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLatencyRoute: AdminLatencyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlugsRoute: AdminSlugsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RSplatRoute: RSplatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksWarmupRoute: ApiPublicHooksWarmupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
